proyecto_m/carro/urls.py
from django.urls import path

from .import views

app_name="carro"#evitar la colicion 

urlpatterns = [
    
    path('agregar/<int:hamburguesas_id>/', views.agregar_producto, name="agregar"),
    path('eliminar/<int:hamburguesas_id>/', views.eliminar_productos, name="eliminar"),
    path('restar/<int:hamburguesas_id>/', views.restar_productos, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),

]

proyecto_m/proyecto_m/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views as core_views
from productos import views as productos_views
from acerca import views as acerca_views
from django.conf import settings 
from registration import views as registration_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',productos_views.home,{'categoriasprod_id': 1}, name='inicio'),
    
    path('car/',core_views.car, name='car'),
    
    path('carro/', include('carro.urls')),
    
    path('pedidos/', include('pedidos.urls')),

    
    path('accounts/', include('django.contrib.auth.urls')),#IMPORTAR LA LIBRERIA PARA PODER UTILIZARLA EN EL LOGIN
    path('accounts/', include('registration.urls')),
      
    path('acerca/',acerca_views.acerca, name='acerca'),
    #url hamburguesas
    path('hamburguesa_s/',core_views.hamburguesa_s, name='hamburguesa_s'),
    path('hamburguesasuper/',core_views.hamburguesasuper, name='hamburguesasuper'),
    path('hamburguesamexi/',core_views.hamburguesamexi, name='hamburguesamexi'),
    path('hamburguesabri/',core_views.hamburguesabri, name='hamburguesabri'),
    #urls perros
    path('perrosencillo/',core_views.perrosencillo, name='perrosencillo'),
    path('perroamericano/',core_views.perroamericano, name='perroamericano'),
    path('choriperro/',core_views.choriperro, name='choriperro'),
    path('perroran/',core_views.perroran, name='perroran'),
    path('perroteque/',core_views.perroteque, name='perroteque'),
    
    #urls salchipapas
    path('salchisenci/',core_views.salchisenci, name='salchisenci'),
    path('chorisenci/',core_views.chorisenci, name='chorisenci'),
    path('salchiespe/',core_views.salchiespe, name='salchiespe'),
    path('choriespe/',core_views.choriespe, name='choriespe'),
    path('mixsuper/',core_views.mixsuper, name='mixsuper'),
    #picadas 
    path('morropla/',core_views.morropla, name='morropla'),
    path('nevatol/',core_views.nevatol, name='nevatol'),
    path('everest/',core_views.everest, name='everest'),
    path('superm/',core_views.superm, name='superm'),
    #costillas y alitas
    path('costillase/',core_views.costillase, name='costillase'),
    path('costillaes/',core_views.costillaes, name='costillaes'),
    path('costillasup/',core_views.costillasup, name='costillasup'),
    path('alitasp/',core_views.alitasp, name='alitasp'),
    path('mixta/',core_views.mixta, name='mixta'),
    
    #porciones
    path('porcionp/',core_views.porcionp, name='porcionp'),
    path('porcionh/',core_views.porcionh, name='porcionh'), 

    path('pedidos/', include('pedidos.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

proyecto_m/productos/models.py
from django.db import models

# Create your models here.
class categoriasprod(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')
    
    class Meta:
        verbose_name="categoiriaProd"
        verbose_name_plural="categoriasProd"
        ordering = ["created"] 
        
    def __str__(self):
        return self.title

class hamburguesas(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    categorias=models.ForeignKey(categoriasprod, on_delete=models.CASCADE)
    image1=models.ImageField(verbose_name='Imagen1',upload_to="productos")#upload para que las imagenes guardadas se hagan en el directorio projects
    descrip=models.TextField(verbose_name="Descripcion")
    precio=models.FloatField(verbose_name='precio', null=True)
    link=models.URLField(verbose_name="Direccion Web", null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')

    class Meta:
        verbose_name = "hamburguesa"
        verbose_name_plural = "hamburguesas"
        ordering = ["created"] 

    def __str__(self):
        return self.title  # <=====

proyecto_m/productos/views.py
from django.shortcuts import render,redirect
from .models import hamburguesas,categoriasprod
from carro.carro import Carro


# Create your views here.

def home(request, categoriasprod_id): #esperar una respuesta (request)
    categorias = categoriasprod.objects.all()
    cate1 = categoriasprod.objects.get(id=1)
    cate2 = categoriasprod.objects.get(id=2)
    cate3 = categoriasprod.objects.get(id=3)
    cate5 = categoriasprod.objects.get(id=5)
    cate6 = categoriasprod.objects.get(id=6)
    cate7 = categoriasprod.objects.get(id=10)
    carro = Carro(request)
    return render(request,'productos/home.html',{'categorias':categorias,'cate1':cate1,
                'cate2':cate2,'cate3':cate3,'cate5':cate5,'cate6':cate6,
                'cate7':cate7})

proyecto_m/productos/templates/productos/home.html
{% extends 'core/base.html'%}

{% load static %}
<title>{% block title %}Mountain Burger{% endblock %}</title>

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<section>
    <h1 class="titulo_categorias">CATEGORIAS</h1>
    <ul class="categorias">
      <li><a href="#{{cate1.id}}"><img src="{% static 'core/img/burger.png'%}" alt="" width="30" height="30" style="margin: 5px 5px 0 0;">HAMBURGUESAS</a></li>
      <li><a href="#{{cate2.id}}"><img src="{% static 'core/img/pancho.png'%}" alt="" width="30" height="30" style="margin: 5px 5px 0 0;"> PERROS</a></li>
      <li><a href="#{{cate3.id}}"><img src="{% static 'core/img/papas-fritas.png'%}" alt="" width="30" height="30" style="margin: 5px 5px 0 0;">SALCHIPAPA</a></li>
      <li><a href="#{{cate5.id}}"><img src="{% static 'core/img/picada.png'%}" alt="" width="30" height="30" style="margin: 5px 5px 0 0;">PICADA</a></li>
      <li><a href="#{{cate6.id}}"><img src="{% static 'core/img/costillas.png'%}" alt="" width="30" height="30" style="margin: 5px 5px 0 0;">COSTILLAS Y ALITAS</a></li>
    </ul>
    <ul class="categorias1">
      <li><a href="#{{cate7.id}}"><img src="{% static 'core/img/papitas.png'%}" alt="" width="30" height="30" style="margin: 0 5px 5px 0;">PORCIONES ADICIONALES</a></li>
      </ul>
  </section>
  <!--aqui va datos-->

    <div id="cuerpo2">
      <div id="carta">
        <hr style="background-color: rgb(242, 172, 41); border: dashed 10px">
       <h2>CARTA</h2>
      </div>
      <div id="horario">
       <h2>Horario: 4:00 pm 12:00 am</h2>
      </div>
    </div>
    <br>
    <hr style="background-color: rgb(242, 172, 41);border: dashed 10px">
<!--aqui ira el carrusel de los productos y su descripcion-->



{% for categoriasprod in categorias %}
<br>

<a name="{{categoriasprod.id}}"></a>
<h2 class="title-burger">{{categoriasprod.title}}</h2>

<div class="grid-container">
  {% for hamburguesas in categoriasprod.hamburguesas_set.all %}
<div class="grid-item">
<img src="{{hamburguesas.image1.url}}" alt="" class="img-caja">
<h3>{{ hamburguesas.title}}</h3>
<p style="text-align: center;">$ {{ hamburguesas.precio|floatformat:3}}</p>
{% if hamburguesas.link %}
<a href="{{hamburguesas.link}}">Saber Mas</a>
<h1 class="title-burger">{{produ.categorias.title}}</h1>

{% endif %}
</div>
{% endfor %}
</div>
{% endfor %}
<br>
<br>

<!--BOTON DE IR HACIA ARRIBA-->
<div id="button-up">
  <i class="fas fa-chevron-up" style="color: aliceblue;"></i> 
</div>

<script>
document.getElementById("button-up").addEventListener("click", scrollUp);
function scrollUp(){
  var currentScroll = document.documentElement.scrollTop; /*me va obtener el scroll*/
  if (currentScroll > 0){
    window.scrollTo (0, 0);
    buttonUp.style.transform = "scale(0)"; /*cuando se le de click al boton desaparezca*/
  }
}

buttonUp = document.getElementById("button-up");

window.onscroll = function(){
  var scroll = document.documentElement.scrollTop;/*se guarda la posicion del scroll*/

  if (scroll > 900){
    buttonUp.style.transform = "scale(1)";
  }
  else if(scroll < 900){
    buttonUp.style.transform = "scale(0)";
  }
}
</script>
{% endblock %}