proyecto_m/carro/urls.py
from django.urls import path

from .import views

app_name="carro"#evitar la colicion 

urlpatterns = [
    
    path('agregar/<int:hamburguesas_id>/', views.agregar_producto, name="agregar"),
    path('eliminar/<int:hamburguesas_id>/', views.eliminar_productos, name="eliminar"),
    path('restar/<int:hamburguesas_id>/', views.restar_productos, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),

]

proyecto_m/proyecto_m/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views as core_views
from productos import views as productos_views
from acerca import views as acerca_views
from django.conf import settings 
from registration import views as registration_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',productos_views.home,{'categoriasprod_id': 1}, name='inicio'),
    
    path('car/',core_views.car, name='car'),
    
    path('carro/', include('carro.urls')),
    
    path('pedidos/', include('pedidos.urls')),

    
    path('accounts/', include('django.contrib.auth.urls')),#IMPORTAR LA LIBRERIA PARA PODER UTILIZARLA EN EL LOGIN
    path('accounts/', include('registration.urls')),
      
    path('acerca/',acerca_views.acerca, name='acerca'),
    #url hamburguesas
    path('hamburguesa_s/',core_views.hamburguesa_s, name='hamburguesa_s'),
    path('hamburguesasuper/',core_views.hamburguesasuper, name='hamburguesasuper'),
    path('hamburguesamexi/',core_views.hamburguesamexi, name='hamburguesamexi'),
    path('hamburguesabri/',core_views.hamburguesabri, name='hamburguesabri'),
    #urls perros
    path('perrosencillo/',core_views.perrosencillo, name='perrosencillo'),
    path('perroamericano/',core_views.perroamericano, name='perroamericano'),
    path('choriperro/',core_views.choriperro, name='choriperro'),
    path('perroran/',core_views.perroran, name='perroran'),
    path('perroteque/',core_views.perroteque, name='perroteque'),
    
    #urls salchipapas
    path('salchisenci/',core_views.salchisenci, name='salchisenci'),
    path('chorisenci/',core_views.chorisenci, name='chorisenci'),
    path('salchiespe/',core_views.salchiespe, name='salchiespe'),
    path('choriespe/',core_views.choriespe, name='choriespe'),
    path('mixsuper/',core_views.mixsuper, name='mixsuper'),
    #picadas 
    path('morropla/',core_views.morropla, name='morropla'),
    path('nevatol/',core_views.nevatol, name='nevatol'),
    path('everest/',core_views.everest, name='everest'),
    path('superm/',core_views.superm, name='superm'),
    #costillas y alitas
    path('costillase/',core_views.costillase, name='costillase'),
    path('costillaes/',core_views.costillaes, name='costillaes'),
    path('costillasup/',core_views.costillasup, name='costillasup'),
    path('alitasp/',core_views.alitasp, name='alitasp'),
    path('mixta/',core_views.mixta, name='mixta'),
    
    #porciones
    path('porcionp/',core_views.porcionp, name='porcionp'),
    path('porcionh/',core_views.porcionh, name='porcionh'), 

    path('pedidos/', include('pedidos.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

proyecto_m/carro/models.py
from django.db import models

# Create your models here.

proyecto_m/productos/models.py
from django.db import models

# Create your models here.
class categoriasprod(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')
    
    class Meta:
        verbose_name="categoiriaProd"
        verbose_name_plural="categoriasProd"
        ordering = ["created"] 
        
    def __str__(self):
        return self.title

class hamburguesas(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    categorias=models.ForeignKey(categoriasprod, on_delete=models.CASCADE)
    image1=models.ImageField(verbose_name='Imagen1',upload_to="productos")#upload para que las imagenes guardadas se hagan en el directorio projects
    descrip=models.TextField(verbose_name="Descripcion")
    precio=models.FloatField(verbose_name='precio', null=True)
    link=models.URLField(verbose_name="Direccion Web", null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')

    class Meta:
        verbose_name = "hamburguesa"
        verbose_name_plural = "hamburguesas"
        ordering = ["created"] 

    def __str__(self):
        return self.title  # <=====

proyecto_m/carro/views.py
from django.shortcuts import render
from .carro import Carro
from productos.models import hamburguesas
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, hamburguesas_id):
    
    carro=Carro(request)
        
    hamburguesa=hamburguesas.objects.get(id=hamburguesas_id)
    
        
    carro.agregar(hamburguesas=hamburguesa)
    
    return redirect("car")

def eliminar_productos(request, hamburguesas_id):
    carro = Carro(request)
    
    hamburguesa=hamburguesas.objects.get(id=hamburguesas_id)
    
    carro.eliminar(hamburguesas=hamburguesa)
    
    return redirect("car")

def restar_productos(request, hamburguesas_id):
    carro = Carro(request)

    hamburguesa=hamburguesas.objects.get(id=hamburguesas_id)
    
    carro.restar_producto(hamburguesas=hamburguesa)
    
    return redirect("car")

def limpiar_carro(request):
    
    carro = Carro(request)
    
    carro.limpiar_carro()
    
    return redirect("car")

proyecto_m/productos/views.py
from django.shortcuts import render,redirect
from .models import hamburguesas,categoriasprod
from carro.carro import Carro


# Create your views here.

def home(request, categoriasprod_id): #esperar una respuesta (request)
    categorias = categoriasprod.objects.all()
    cate1 = categoriasprod.objects.get(id=1)
    cate2 = categoriasprod.objects.get(id=2)
    cate3 = categoriasprod.objects.get(id=3)
    cate5 = categoriasprod.objects.get(id=5)
    cate6 = categoriasprod.objects.get(id=6)
    cate7 = categoriasprod.objects.get(id=10)
    carro = Carro(request)
    return render(request,'productos/home.html',{'categorias':categorias,'cate1':cate1,
                'cate2':cate2,'cate3':cate3,'cate5':cate5,'cate6':cate6,
                'cate7':cate7})

proyecto_m/productos/templates/carro/widget.html
<div class="caja_carrito">

<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th>Productos</th>
            <th>Nombre Producto</th>
            <th>Cantidad</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>
                        <img src="{{value.imagen}}" alt="" width="150px"></td>

    
                    <td class="datos_carro"><p>{{value.nombre}}</p></td>

                    <td class="datos_cant">
                        <a href="{% url 'carro:restar' value.hamburguesas_id %}" class="boton_restar"><b>-</b></a>

                        <b class="caja_cant">{{value.cantidad}}</b>

                        <a href="{% url 'carro:agregar' value.hamburguesas_id %}" class="boton_sumar"><b>+</b></a>

                    </td>
                    
                    <td>
                        <b class="datos_precio">{{value.precio|floatformat:3}} $</b>
                    </td>

                    <td class="datos_borrar">
                        <b><a href="{% url 'carro:eliminar' value.hamburguesas_id  %}" ><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="rgb(222, 147, 18)" class="bi bi-trash-fill" viewBox="0 0 16 16">
                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                      </svg>
                        </td>
                            </b>
                                </tr>      
            {% endfor %}
            <tfoot>
                <td colspan="6">
                    <form action="{% url 'carro:limpiar' %}" method="post">
                        {% csrf_token %}
                            <button type="submit" class="boton-vaciar">Vaciar carrito</button>
                </form>
                </td>
            </tfoot>
        {% else %}
            <tr>
                <td colspan="5">
                    <div class="alert alert-danger text-center">
                        SIN PRODUCTOS
                    </div>
                </td>
            </tr>
        {% endif %}
        </tbody>

</table>
{% if request.session.carro.items %}
<p class="p_total">Total a pagar = $ {{importe_total_carro|floatformat:3}}</p>
{% endif %}
</div>
<script>
    function redirectToURL(url) {
      window.location.href = url;
    }
  </script>